name: Generate Snake Game from Contribution Grid

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *" # Runs daily at midnight UTC

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake Game from GitHub Contribution Grid
        uses: Platane/snk@v3.0.0
        with:
          github_user_name: TisAvm
          outputs: |
            dark.svg?palette=github-dark&color_snake=blue
            light.svg?color_snake=#7845ab
            ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9
